USE PEDIDOS
 
SELECT NUM_PEDIDO, DATA_EMISSAO,VLR_TOTAL, TB_VENDEDOR.NOME
FROM TB_PEDIDO
JOIN TB_VENDEDOR ON TB_VENDEDOR.CODVEN = TB_PEDIDO.CODVEN

SELECT NUM_PEDIDO, DATA_EMISSAO,VLR_TOTAL, TB_CLIENTE.NOME
FROM TB_PEDIDO
JOIN TB_CLIENTE ON TB_CLIENTE.CODCLI = TB_PEDIDO.CODCLI

SELECT NUM_PEDIDO, TB_VENDEDOR.NOME ,TB_CLIENTE.NOME
FROM TB_PEDIDO , TB_VENDEDOR
JOIN TB_CLIENTE ON TB_CLIENTE.NOME = TB_CLIENTE.NOME

SELECT DESCRICAO , TB_ITENSPEDIDO.COD_PRODUTO
FROM TB_PRODUTO
JOIN TB_ITENSPEDIDO ON TB_ITENSPEDIDO.ID_PRODUTO =   TB_ITENSPEDIDO.ID_PRODUTO


SELECT DESCRICAO , TB_PRODUTO.COD_PRODUTO , TB_TIPOPRODUTO.TIPO
FROM TB_PRODUTO
JOIN TB_TIPOPRODUTO ON TB_TIPOPRODUTO.TIPO = TB_TIPOPRODUTO.TIPO

SELECT COD_PRODUTO, DESCRICAO, U.UNIDADE, TP.TIPO
FROM TB_PRODUTO PR
JOIN TB_UNIDADE U ON PR.COD_UNIDADE = U.COD_UNIDADE

SELECT NUM_PEDIDO, NUM_ITEM, IT.COD_PRODUTO, QUANTIDADE, PR_UNITARIO, PR.COD_PRODUTO, PR.DESCRICAO
FROM TB_ITENSPEDIDO IT
JOIN TB_PRODUTO PR ON PR.COD_PRODUTO = IT.COD_PRODUTO


SELECT NUM_PEDIDO,NUM_ITEM, IT.COD_PRODUTO,IT.QUANTIDADE,PR_UNITARIO, PR.DESCRICAO, C.COR, TPPR.TIPO, U.UNIDADE
FROM TB_ITENSPEDIDO IT
JOIN TB_PRODUTO PR ON PR.COD_PRODUTO = IT.COD_PRODUTO
JOIN TB_COR C ON IT.CODCOR = C.CODCOR
JOIN TB_TIPOPRODUTO TPPR ON PR.COD_TIPO = TPPR.COD_TIPO
JOIN TB_UNIDADE U ON PR.COD_UNIDADE = U.COD_UNIDADE

SELECT * FROM TB_PEDIDO P
JOIN TB_VENDEDOR V ON NOME = 'MARCELO'
WHERE P.DATA_EMISSAO BETWEEN '2017-01-01' AND '2017-01-31'

SELECT NOME, P.DATA_EMISSAO FROM TB_CLIENTE
JOIN TB_PEDIDO P ON P.DATA_EMISSAO BETWEEN '2017-01-01' AND '2017-01-31'

SELECT DESCRICAO FROM TB_PRODUTO PR
JOIN TB_PEDIDO P ON P.DATA_EMISSAO BETWEEN '2017-01-01' AND '2017-01-31'

SELECT DESCRICAO,TB_FORNECEDOR.NOME
FROM TB_PRODUTO
JOIN TB_FORNECEDOR ON TB_FORNECEDOR.NOME LIKE 'LINCE% '